export const GET_RECIPES = 'GET_RECIPES';
export const ADD_RECIPES = 'ADD_RECIPES';
export const DELETE_RECIPES = 'DELETE_RECIPES';

export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const DELETE_INGREDIENTS = 'DELETE_INGREDIENTS';
